version: '3'

services:
  tor-relay:
    container_name: tor-relay
    image: ams21/tor-relay:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - tor-relay-network
    environment:
      # You need to forward these ports
      - OR_PORT=443
      - DIR_PORT=80
      - EMAIL=you@email.com
      - NICKNAME=DockerTorRelay
      # - TORRC_Address=<IP4-Address>
    ports:
      - 127.0.0.1:9050:9050
      - 127.0.0.1:9051:9051
      - ${OR_PORT}:${OR_PORT}
      - ${DIR_PORT}:${DIR_PORT}
    volumes:
      - data:/var/lib/tor

networks:
  tor-relay-network:
    name: tor-relay

volumes:
  data:
    name: tor-relay-data
